name: Blisss
favicon: null
layout_spectrum: 0.4104372139554471
typography_spectrum: 0.2137
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272727'
    - '#f7f7f7'
    - '#999999'
    - '#33ef74'
    - '#984a35'
  brandStrength: 0.9375
  lightness: 0.7560943863354623
  saturation: 0.9385753420647234
  rhythmicContrast: 0.5674787133466452
purpose: []
