typography_spectrum: 0.20987
color:
  brandColors:
    - '#191919'
    - '#03a2e1'
    - '#4f4f4f'
    - '#f2f2f2'
    - '#e30a14'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5674787133466452
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03753
analytics:
  google: null
  facebook: null
  twitter: null
name: Bliss
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Testing the Grid
purpose: []
